### PR TITLE
fix redirect issue

### LINKED ISSUE #27: Using loginRedirect doesn't get handled properly
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Originally I used `loginPopup` to login a user if there were no tokens present but I've now moved to using `loginRedirect` and have setup the `handleRedirectPromise` to deal with this. My app calls the `login` part automatically when you hit it, so there is no button to press and what I am finding is the following cycle:

- User goes to app and hits `loginRedirect`
- Browser goes to MS to get token and comes back to the RedirectUrl which is the same app
- User still not authenticated so hits `loginRedirect` again but this throws an error
   - ` BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.`
- Promise from MS is returned and `handleRedirectPromise` is hit, user is authenticated

A colleague of mine is using the older version of `msal-browser 1.3` and has the same scenario but he does not receive this error and he has found that there is code that actually handles this within the script of `msal-browser`.

Am I doing something wrong here or is this a bug? I can easily manage this scenario by setting a `sessionStorage` entry to indicate login in already in progress.

### PR DESCRIPTION
**Pull request by derisen**
This PR fixes the issue with redirect flow where Redux store is updated by null value due to application state being lost during page redirect, causing UI not to update even though authentication is completed.

### CODE REVIEW

**Comment by dfibuch** [comment]
@derisen Has this fix been released yet?

**Comment by derisen** [comment]
@dfibuch PR was merged already. The issue should be resolved now. Please let us know if you still run into it.

**Comment by dfibuch** [comment]
Hmmm ye still seeing it, let me double check I am using the latest version, etc.

**Comment by dfibuch** [comment]
@derisen I'm still seeing the error with v2.1 installed. Is it ok that when the user is redirected back to my app from the login page they then hit `loginRedirect` again, before we've my `handleRedirectPromise` is hit? Or should I set the `RedirectUrl` to some sort of loading page that waits for the `handleRedirectPromise` to be hit, and then in that method once I get my token I can redirect the user internally to the home page? That would avoid hitting `loginRedirect` twice.

**Comment by derisen** [comment]
@dfibuch that's interesting, I'm not seeing this on my logs. Would you mind sharing yours? It might be that you are not invoking `handleRedirectPromise()` before calling `loginRedirect` -in the sample, this is done immediately when the component mounts. Then the rest seems normal: 

1. `handleRedirectPromise `returns `null `when the app is first loaded.
2. `handleRedirectPromise `returns response object after app redirects.

**Comment by dfibuch** [comment]
Yea you're right, my `loginRedirect` is called before my `handleRedirectPromise` when I come back to the app after sign in, so it's my fault. I misunderstood the flow, sorry. I have a plan how to resolve it in my case.

I just assumed that the `msalApp` would know and ignore a 2nd login request if first one is in progress already, which I thought was the behaviour in 1.3.0.

Consider this resolved and thanks again for your help.

**Comment by derisen** [comment]
@dfibuch no worries : ) There's [a discussion here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2104) that gets more into the details.

**Pull request merged**
